apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: prow
    app: cherrypicker
  namespace: default
  name: cherrypicker
spec:
  selector:
    app: cherrypicker
  ports:
  - name: http
    port: 80
    targetPort: http
  type: ClusterIP
