apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: deck
  labels:
    app.kubernetes.io/part-of: prow
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: deck
  labels:
    app.kubernetes.io/part-of: prow
rules:
- apiGroups:
  - "prow.k8s.io"
  resources:
  - prowjobs
  verbs:
  - get
  - list
  - watch
  # Required when deck runs with `--rerun-creates-job=true`
  - create
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-pods
  name: deck
  labels:
    app.kubernetes.io/part-of: prow
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: deck
  labels:
    app.kubernetes.io/part-of: prow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deck
subjects:
- kind: ServiceAccount
  name: deck
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-pods
  name: deck
  labels:
    app.kubernetes.io/part-of: prow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deck
subjects:
- kind: ServiceAccount
  name: deck
  namespace: default
