apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: "horologium"
  labels:
    app.kubernetes.io/part-of: prow
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: "horologium"
  labels:
    app.kubernetes.io/part-of: prow
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - create
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: "horologium"
  labels:
    app.kubernetes.io/part-of: prow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "horologium"
subjects:
- kind: ServiceAccount
  name: "horologium"
